### ISSUE TITLE
Feature request: summarised species-level distance table

### ISSUE THREAD

**Issue by markscherz** [iTaxoTools/TaxIGui#2]
Current output of distance tables is very difficult to convert into a publishable format, but the software already outputs all the information that would be needed to generate a standardisable summary of distances, specifically in the subsets > species.pairs.tsv table. This table is given in list format, with the p min, p max, and p mean in a 'melted' format for every pairwise comparison. This could be given instead as a matrix:

```
ref,sp_a,sp_b,sp_c
sp_a,mean (min–max),mean (min–max),mean (min–max)
sp_b,mean (min–max),mean (min–max),mean (min–max)
sp_c,mean (min–max),mean (min–max),mean (min–max)
```
This is the actual format we use in publications. Getting to this manually from the current table is extremely annoying.

**Comment by mvences** [comment]
Indeed this will be important to add, I ran into the same problem today. We will need matricial output at the level of species (and genera) giving min-max (mean) for all species pairs. This was implemented in Vladimir's earlier version of TaxI2 but "disappeared" from the new version. It will be included in the next version, probably in a couple of weeks once we realize additional bugs and issues and receive reviewer comments. I will also create 1-2 other issues, and I have added Stefanos as assignee here to make sure he is informed.

**Comment by StefanPatman** [comment]
Matricial output for species and genera distances has just been added to the backend. This is currently in the form @markscherz suggested: `mean (min-max)`, but could be changed or parametrized if needed.

It will be included in the next Gui executable, as @mvences mentioned.

**Comment by mvences** [comment]
I have now been able to check and test the new version of the program. I have closed two issues that I think should be now fixed, but we still need some work on the matricial output.

First, I noted a bug when clicking the "genus" option in the Against all procedure. In the example file I used, all sequences belonged to the same genus, and the program probably did not know how to deal with this:
- In the summary.tsv table, distance comparisons that were clearly "inter-species" (i.e., belonging to two different species of the same genus) were flagged as "inter-genus".
- In the subsets file for genera, the files looked very weird, with sequences rather than taxon names and so on ... not unexpected, because in fact, in this dataset, there were no genera to compare.
So, overall, the procedure of the "Perform genus analysis" option needs to be revised. Basically, if this option is selected and all sequences are of the same genus, then no "genus" output at all should be produced, and comparisons among different species should be flagged as "inter-species".
[note that the programs performs well both (i) when all sequences belong to the same genus and the genus option is not selected, and (ii) when the file does contain sequences of different genera and the genus option is selected]


Secondly, for the matricial output. It is good now, showing the mean followed by range in parentheses. But there will be cases when users want a slightly different representation, and especially for large matrices, it will be hard to adjust this manually. So we have two options:
1. The "perfectionist" option that @Stefanos you will probably like best ... add in the GUI the option to "customize" the matrix output. To avoid making it too complex, I would give perhaps a drop-down menu with many options: 
- mean
- minimum
- maximum
- mean (minimum-maximum)
- minimum-maximum
- minimum-maximum (mean)
and then, the matrices are all produced in the selected form.
2. Alternatively, we could produce the three or four most "typical" options automatically, which will of course inflate the output with more files. Then I would restrict this to 
- mean
- mean (minimum-maximum)
- minimum-maximum











-

**Comment by markscherz** [comment]
One note about the current implementation of the species-summary distance tables: the diagonal (intraspecific variation) includes comparisons of all individuals to themselves. These are always 0%, but self values are meaningless. It should ideally not be including self comparisons; neither in the calculation of the mean, nor in the summary of the range.

**Comment by mvences** [comment]
Hello Mark, good point, we need to look into this carefully, to make sure we don't introduce any new mistake, but indeed self-comparisons should not be done in the calculation of intraspecific distances. It is weird that you say such comparisons are included, normally in Vladimir's script they were not calculated.

**Comment by markscherz** [comment]
Indeed. The diagonal includes 0.0 in the range for all species, including those where N = 1, making it clear that there is self-comparison included. This is based on the latest version compiled from source this afternoon (2023-04-11).
<img width="1226" alt="Screenshot 2023-04-11 at 21 55 51" src="https://user-images.githubusercontent.com/46906676/231274317-2e400fe6-329c-4d0c-a80a-e8f2a7d28755.png">
Modalities: 
Already aligned
Uncorrected p-distance
Distances as percentage
1 decimal point
Not-Available Symbol: NA

**Comment by StefanPatman** [comment]
Thank you for reporting this. I removed the sample self-comparisons from intraspecific subset comparisons.

It is now possible to select a "template" for the distance summaries. This template can be selected from a list of common options (suggested by Miguel above) or customised by the user, in the form of text containing the words "mean", "minimum" or "maximum", which are then replaced by the corresponding values. For example, a template of "mean: minimum/maximum" may become "0.2: 0.1/0.3"

If you are running from source, you will need to update both frontend and backend for the changes to work.
One way to do this is from within the cloned repository:
```
cd TaxIGui
git pull
pip install --force-reinstall --no-deps taxi2 -f packages.html
```

**Comment by StefanPatman** [comment]
All discussed changes are now applied to the latest executables.
